
[client]
toolbarMode = "viewer"
showSidebarNavigation = false
showErrorDetails = false


[browser]
gatherUsageStats = false

[theme]
base="dark"
font="sans serif"
primaryColor="#e28743"
backgroundColor ="#000000"

[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = false
